name: test

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/openwrt_x86.yml'
      - 'x86.config'
      - 'feeds.conf'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
        - "true"
        - "false"
      debug:
        description: 'Debug mode'
        required: true
        default: 'false'
        type: choice
        options:
        - "true"
        - "false"
jobs:
    build_openwrt:
      name: Build OpenWrt firmware
      runs-on: ubuntu-24.04
      if: github.event.repository.owner.id == github.event.sender.id
      permissions: write-all
      env:
        DEPENDENCIES: "build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget"
        REPO_BRANCH: main
        BUILD_OPENWRT: ${{ github.workspace }}/openwrt_source_code
        BUILD_ROOT: ${{ github.workspace }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        TZ: Asia/Shanghai
        DEVICE_NAME: unknown
        FILE_DATE: unknown
        FIRMWARE: unknown
        Architecture: amd64
      steps:
        - name: test
          if: github.event.inputs.debug == 'false'
          run: |
            echo "debug mode"
        - name: Checkout
          uses: actions/checkout@main
        - name: test custom.sh
          run: |
            cd $BUILD_ROOT
            echo "test custom.sh"
            bash custom.sh $ARCHITECTURE $BUILD_ROOT
